name: Run tests
on:
  push:
    branches:
      - tests
  pull_request:
    branches:
      - tests
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v2
      - name: setup npm
        run: |
          curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs
      - name: run tests
        run: npm run test
